### ISSUE TITLE
investigate reset issue

### ISSUE THREAD

**Issue by roussel-ryan** [slaclab/Badger#56] opened 2024-04-15 21:07 UTC

**Comment by wenatuhs** [comment] 2024-04-25 17:43
The reset issue was caused by None values in the returned dictionary of the `get_variables` call. The fix should be put into the corresponding environment/interface.

**Comment by wenatuhs** [comment] 2024-04-30 06:53
Fixed in 0bae819eef2a1229cef31b1f1e7116ac47c58e47

**Closed** 2024-04-30 06:56 UTC
